import { StyleSheet } from "react-native";

export default styles = StyleSheet.create({
    container: {
        marginTop: 5,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sliderWrapper: {
        width: '100%',
        height: 190,
    },
    flatListContent: {
        gap: 10,
    },
    sliderItem: {
        width: width * 0.878,
        borderRadius: 20,
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    sliderTile: {
        width: "100%",
        height: "100%",
        overflow: "hidden",
        objectFit: "cover",
    },
    image: {
        width: "100%",
        height: "100%",
        resizeMode: "cover",
        borderRadius: 15,
    },
    sliderText: {
        position: "absolute",
        bottom: 15,
        fontFamily: "sans-serif-regular",
        fontSize: 14,
        backgroundColor: 'rgba(0,0,0,0.5)',
        color: "white",
        paddingVertical: 3,
        paddingHorizontal: 30,
        borderRadius: 20,
    },
    btnContainer: {
        width: '100%',
        height: '10%',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 10,
        marginTop: 10,
        marginBottom: 5,
    },
    arrowContainer: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingLeft: 7,
        paddingRight: 10,
        position: "absolute",
        top: "37%",
    },
    arrowBtnLeft: {
        backgroundColor: 'rgba(0,0,0,0.5)',
        width: 30,
        height: 30,
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
        paddingRight: 3,
    },
    arrowBtnRight: {
        backgroundColor: 'rgba(0,0,0,0.5)',
        width: 30,
        height: 30,
        borderRadius: 50,
        justifyContent: "center",
        alignItems: "center",
        paddingLeft: 3,
    },
});
